# Generated by Django 4.2.7 on 2024-01-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='pt_app.exercise'),
        ),
    ]
