# Generated by Django 4.2.7 on 2024-02-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='number',
        ),
        migrations.AddField(
            model_name='phase',
            name='name',
            field=models.CharField(default='No Name', max_length=120),
        ),
    ]
