# Generated by Django 4.2.7 on 2024-03-04 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0002_remove_phase_number_phase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgramProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('current_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pt_app.phase')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='pt_app.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user_program_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='pt_app.userprogramprogress')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pt_app.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.IntegerField(default=0)),
                ('reps_per_set', models.IntegerField(default=0)),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_app.workoutexercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='pt_app.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.IntegerField(default=1)),
                ('current_workout_index', models.IntegerField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='pt_app.phase')),
                ('user_program_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_progress', to='pt_app.userprogramprogress')),
            ],
            options={
                'unique_together': {('user_program_progress', 'phase')},
            },
        ),
    ]
