# Generated by Django 4.2.7 on 2024-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0002_remove_exercise_workout_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
