# Generated by Django 4.2.7 on 2024-03-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0003_userprogramprogress_workoutsession_exerciselog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='reps_per_set',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='video',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='weight_used',
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='pt_app.exerciselog')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('exercise_log', 'set_number')},
            },
        ),
    ]
