# Generated by Django 4.2.7 on 2024-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0005_remove_phaseprogress_current_workout_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='workout_videos/'),
        ),
    ]
