# Generated by Django 4.2.7 on 2024-02-12 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pt_app', '0005_alter_program_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
