# Generated by Django 4.2.7 on 2024-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0006_alter_program_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default='No description'),
        ),
    ]
