# Generated by Django 4.2.7 on 2024-03-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0007_workoutexercise_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
