# Generated by Django 4.2.7 on 2024-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0008_remove_workoutexercise_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
