# Generated by Django 4.2.7 on 2024-03-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0009_remove_workoutexercise_video_exercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
