# Generated by Django 4.2.7 on 2024-03-17 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0010_alter_exercise_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseset',
            options={'ordering': ['exercise_log']},
        ),
        migrations.AlterUniqueTogether(
            name='exerciseset',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
