# Generated by Django 4.2.7 on 2024-03-18 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0011_alter_exerciseset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='creator',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='created_workouts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
