# Generated by Django 4.2.7 on 2024-04-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0014_chatsession_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='active',
            field=models.BooleanField(default=True)
        ),
    ]
