# Generated by Django 4.2.7 on 2024-04-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0016_alter_exerciseset_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
