# Generated by Django 4.2.7 on 2024-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0017_exerciseset_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
