# Generated by Django 4.2.7 on 2024-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0018_alter_exerciseset_reps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseset',
            options={'ordering': ['set_number']},
        ),
        migrations.AddField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
