# Generated by Django 4.2.7 on 2024-04-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0019_alter_exerciseset_options_workout_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
