# Generated by Django 4.2.7 on 2024-04-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0020_alter_workoutexercise_options_workoutexercise_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phaseprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phaseprogress',
            name='current_workout_id',
        ),
        migrations.RemoveField(
            model_name='phaseprogress',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='phaseprogress',
            name='user_program_progress',
        ),
        migrations.RemoveField(
            model_name='userprogramprogress',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='phase',
        ),
        migrations.AddField(
            model_name='workout',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='pt_app.program'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='PhaseProgress',
        ),
    ]
