# Generated by Django 4.2.7 on 2024-05-04 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0021_alter_phaseprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
