# Generated by Django 4.2.7 on 2024-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0022_exercise_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
