# Generated by Django 4.2.7 on 2024-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0025_workout_created_at_workout_is_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
