# Generated by Django 4.2.7 on 2024-05-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0027_message_encrypted_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='nonce_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='nonce_sender',
        ),
    ]
