# Generated by Django 4.2.7 on 2024-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0028_remove_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
