# Generated by Django 4.2.7 on 2024-05-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0029_alter_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
