# Generated by Django 4.2.7 on 2024-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0032_trainerrequest_trainerclientrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
