# Generated by Django 4.2.7 on 2024-05-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0035_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_message_recipient',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='encrypted_message_sender',
        ),
    ]
