# Generated by Django 4.2.7 on 2024-05-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0036_rename_encrypted_message_recipient_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_exercises', to='pt_app.workout'),
        ),
    ]
