# Generated by Django 4.2.7 on 2024-05-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0037_alter_workoutexercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
