# Generated by Django 4.2.7 on 2024-05-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_app', '0038_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
    ]
